favicon: null
name: JFVisuals
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.9103115
  brandStrength: 1
  lightness: 0.4985495
  brandColors:
    - '#020201'
    - '#2F2820'
    - '#6E665A'
    - '#A39C90'
    - '#FBFBFB'
  rhythmicContrast: 0.6310419
typography_spectrum: 0.3270676
layout_spectrum: 1
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
